### ISSUE TITLE
Automatically propagate issue templates defined within .github to all org repos.

### ISSUE THREAD

**Issue by aentinger** [107-systems/.github#31]
I thought that all issue templates defined [here(.github/ISSUE_TEMPLATE)](https://github.com/107-systems/.github/tree/main/ISSUE_TEMPLATE) would automatically be propagated across all repos of the org? Somehow that's not true. @per1234 do you know why?

**Comment by per1234** [comment]
There is no capability for automated propagation of workflows to the repos. The only magic is it populates the list of "Workflows created by 107-Systems" on the "New workflow" page of all the repositories of the organization. For example:
https://github.com/107-systems/107-Arduino-UAVCAN/actions/new

![image](https://user-images.githubusercontent.com/8572152/130314840-8bf61130-324a-4c03-b59a-38c50b0fcc9d.png)

Details here:
https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

**Comment by per1234** [comment]
Oops, I didn't read carefully. This is about the issue templates!

**Comment by per1234** [comment]
It says here:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#creating-a-repository-for-default-files
>In the repository, create one of the supported community health files. Issue templates and their configuration file must be in a folder called .github/ISSUE_TEMPLATE

So I think the problem is that `ISSUE_TEMPLATE` folder is in the root of the repository.

**Comment by aentinger** [comment]
Neither #32 nor #33 (your proposal) fixed this. The documentation is somewhat ambiguous :cry:
